

// Get all people
GET http://localhost:3000/api/people/

###

// Get specific person
GET http://localhost:3000/api/people/1

###

// Post new object
POST http://localhost:3000/api/people/ HTTP/1.1
Content-Type: application/json

{
    "name": "Helena"
}

###

// Change object
PUT http://localhost:3000/api/people/5 HTTP/1.1
Content-Type: application/json

{
    "name": "Helena!"
}

###

//Delete specific person
DELETE http://localhost:3000/api/people/1