

// Get all assignments
GET http://localhost:3000/api/assignments/

###

// Get specific assignment
GET http://localhost:3000/api/assignments/rek4r

###

// Post new assignment
POST http://localhost:3000/api/assignments/ HTTP/1.1
Content-Type: application/json

{
    "name": "Christian igen",
    "desc": "Testing server functionality"
}

###

// Post new subtask in assignment
POST http://localhost:3000/api/assignments/rek4r HTTP/1.1
Content-Type: application/json

{
    "desc": "addning new subtask"
}

###

// Change assignment
PUT http://localhost:3000/api/assignments/vobuv HTTP/1.1
Content-Type: application/json

{
    "name": "Christian",
    "desc": "testing"
}

###

// Change subtask in assignment
PUT http://localhost:3000/api/assignments/rek4r/hd HTTP/1.1
Content-Type: application/json

{
    "desc": "changing subtask",
    "status": "new"
}

###

//Delete assignment
DELETE http://localhost:3000/api/assignments/foc1


###

//Delete subtask
DELETE http://localhost:3000/api/assignments/rek4r/hdq